This tutorial is all about the MotifCompendium object. It focuses on the various options you have for building a MotifCompendium object and about the flexible syntax you have for manipulating, modifying, and accessing internal data from MotifCompendium objects.

Let's get started!

We will begin by importing the packages we will need.

In [1]:
import numpy as np
import pandas as pd

import MotifCompendium
import MotifCompendium.utils.loader as utils_loader
import MotifCompendium.utils.motif as utils_motif

This tutorial will be written as if we had access to a 12GB GPU. If you want to run this tutorial yourself but do not have access to a GPU then set `use_gpu=False` and do not set the `max_chunk` parameter.

In [2]:
MotifCompendium.set_compute_options(max_cpus=4, use_gpu=True, max_chunk=1152, progress_bar=True)

# 1 - Building MotifCompendium Objects

In the last tutorial, we saw saw how a MotifCompendium object could be built from Modisco output files.

In [3]:
modisco_dict = {
    "cardiomyocyte": "/oak/stanford/groups/akundaje/salil512/resources/MotifCompendium_Tutorial_Resources/cardiomyocyte_modisco_output.h5",
    "endothelial": "/oak/stanford/groups/akundaje/salil512/resources/MotifCompendium_Tutorial_Resources/endothelial_modisco_output.h5"
}
mc = MotifCompendium.build_from_modisco(modisco_dict)
mc

computing similarities on GPU...: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]

The `build_from_modisco()` function takes in two more optional arguments.

The `modisco_region_width` argument should match the `--window/-w` option used when generating the Modisco objects. By default, this number will be 400 (which matches the tfmodisco-lite default). Don't change this argument unless you specifically know you are dealing with a non-standard Modisco window size.

The `ic` argument is a boolean that indicates whether or not motifs should be information-content scaled when being ingested from Modisco. By default, `ic` is set to `True`. IC-scaling is very helpful for the performance of downstream motif clustering, so it is recommended to never change this option without good reason. If you would like to disable IC-scaling, however, do it by setting `ic=False` as shown below.

In [4]:
modisco_dict = {
    "cardiomyocyte": "/oak/stanford/groups/akundaje/salil512/resources/MotifCompendium_Tutorial_Resources/cardiomyocyte_modisco_output.h5",
    "endothelial": "/oak/stanford/groups/akundaje/salil512/resources/MotifCompendium_Tutorial_Resources/endothelial_modisco_output.h5"
}
mc_no_ic = MotifCompendium.build_from_modisco(modisco_dict, ic=False)
mc_no_ic

computing similarities on GPU...: 100%|██████████| 1/1 [00:00<00:00, 57.35it/s]

Notice how the shapes of the above MotifCompendium motifs is (88, 30, 8). The 88 indicates that there are 88 motifs in the MotifCompendium. The 30 indicates that each motif is 30 base pairs long, and the 8 indicates the possible bases at each position. The number of bases is 8 instead of 4 because the under the hood, when building from Modisco, the motifs are transformed from a 4 channel motif representation (ACGT) to an 8 channel sign-aware representation (A+, A-, C+, C-, G-, G+, T-, T+). This representation is beneficial when working with CWMs because you can represent negative contributions and identify repressive motifs.

Although building a MotifCompendium from Modisco motifs is a common use case, MotifCompendium is designed to work with any motifs. The `build()` function allows you to build MotifCompendium objects by passing in motifs directly. The motifs must be passed in as a *non-negative, normalized* **motif stack**. We define a **motif stack** as an `np.ndarray` of shape `(N, L, C)` where the first dimension is the number of motifs, the second dimension is the length of the motifs, and the third dimension is the number of bases/channels.

We will hold off on discussing non-negativity and normalization immediately, and come back to these requirements in a few cells.

Let's see an example of building a MotifCompendium using `build()` using the motifs in HOCOMOCO13. Note that the MotifCompendium package also provides you the utilities to load PFMs from PFM and MEME files with the `utils_loader.load_pfm()` and `utils_loader.load_meme()` functions. All you have to do is pass in the path to such a file and it will output a tuple of `(motifs, names)`, where `motifs` is a motif stack and `names` is a list of names of each motif.

In [5]:
h13_motifs, motif_names = utils_loader.load_pfm("/oak/stanford/groups/akundaje/salil512/resources/MotifCompendium_Tutorial_Resources/H13CORE_pfms.txt")
print(h13_motifs.shape, len(motif_names))

(1610, 31, 4) 1610

These motifs can now directly be passed to the `build()` function and we will get a MotifCompendium of all the H13 motifs!

In [6]:
mc = MotifCompendium.build(h13_motifs)
mc

computing similarities on GPU...: 100%|██████████| 4/4 [00:00<00:00, 20.37it/s]

The `build()` function can also be passed a `metadata` argument as a `pd.DataFrame`. This will populate the per-motif metadata that you see when you print a MotifCompendium object. Let's see that usage below:

In [7]:
h13_metadata = pd.DataFrame()
h13_metadata["motif_name"] = motif_names
print(h13_metadata)
mc = MotifCompendium.build(h13_motifs, h13_metadata)
mc

                   motif_name
0        AHCTF1.H13CORE.0.B.B
1           AHR.H13CORE.0.P.B
2          AHRR.H13CORE.0.P.C
3         ALX1.H13CORE.0.SM.B
4         ALX3.H13CORE.0.SM.B
...                       ...
1605    ZSCAN12.H13CORE.0.P.B
1606    ZSCAN2.H13CORE.0.PG.A
1607  ZSCAN25.H13CORE.0.PSG.A
1608     ZXDA.H13CORE.0.PSI.A
1609      ZXDB.H13CORE.0.PI.A

[1610 rows x 1 columns]

computing similarities on GPU...: 100%|██████████| 4/4 [00:00<00:00, 25.77it/s]

Now, the MotifCompendium has the names of the HOCOMOCO motifs already populated! Later in this tutorial, we will see how the motif metadata can be provided not just at build time but after the MotifCompendium has already been built, as well.

Earlier, it was mentioned that MotifCompendium takes in a *non-negative, normalized* motif stack. Let's discuss these two properties of motif representations (as represented by a `(L, C) np.ndarray`):
- Non-negativity - We will say that a motif is non-negative if it is >= 0 everywhere.
- Normalized - We will say that a motif is normalized when its sum is 1.

Traditionally, PFMs and PWMs have been non-negative matrix representations of motifs, so they automatically pass the non-negativity requirement. If you were to pass in PFMs/PWMs on your own, you would have to normalize them yourself. However, the `utils_loader.load_pfm()` and `utils_loader.load_meme()` functions automatically normalize the motifs, so their outputs can be passed directly into MotifCompendium.

On the other hand, CWMs (contribution weight matrices), which are learned as features of computational sequence to function models, can contain bases with negative attributions. We don't to lose this important positivity/negativity information but we still want a non-negative matrix because it helps with computing motif similarity. The solution is an 8 channel motif representation, as discussed above.

Below, let's see how you could perform the 4 channel (ACGT) to 8 channel (A+, A-, C+, C-, G-, G+, T-, T+) transformation yourself if you had gotten motifs from Modisco yourself. We will be using the `utils_loader.load_modisco()` function alongside the `utils_motif.motif_4_to_8()` function to perform this transformation.

Also, in addition to outputting the motifs learned by Modisco, `utils_loader.load_from_modisco()` will output the names of the motifs as per Modisco, the number of seqlets that make up each Modisco motif, a classification of each motif by Modisco as either containing a positive motif or a negative motif, and the average distance of the constituent seqlets from peak summits.

In [8]:
modisco_motifs, motif_names, seqlet_counts, posneg, avgdist_summits = utils_loader.load_modisco("/oak/stanford/groups/akundaje/salil512/resources/MotifCompendium_Tutorial_Resources/cardiomyocyte_modisco_output.h5")
modisco_metadata = pd.DataFrame({"name": motif_names, "num_seqlets": seqlet_counts, "posneg": posneg, "avg_dist_from_summit": avgdist_summits})
modisco_motifs_8 = utils_motif.motif_4_to_8(modisco_motifs)
mc = MotifCompendium.build(modisco_motifs_8)
mc

computing similarities on GPU...: 100%|██████████| 1/1 [00:00<00:00, 79.19it/s]

The `utils_loader.load_from_modisco()` function takes care of pre-normalizing the motifs. However, if you had another source of un-normalized CWMs, here is a pattern you could use to build a MotifCompendium.

In [9]:
random_motifs = np.random.rand(100, 30, 4) - 0.5
random_motifs_8 = utils_motif.motif_4_to_8(random_motifs)
random_motifs_8 /= np.sum(random_motifs_8, axis=(1, 2), keepdims=True)
mc = MotifCompendium.build(random_motifs_8)
mc

computing similarities on GPU...: 100%|██████████| 1/1 [00:00<00:00, 74.60it/s]

The final thing to know about building MotifCompendium objects is the `safe` option. By default, the `load()`, `build()`, and `build_from_modisco()` functions all have an option called `safe`. `safe` is a boolean that determines whether or not object integrity checks are performed at the time of object instantiation. By default, `safe` is set to `True`, but it can be overridden to be `False`. While these checks can help guarantee object integrity, they can be computationally costly, especially for extremely large MotifCompendium.

In general, it is best practice to let `safe` be `True` by default. However, if a MotifCompendium object is very large or you use it frequently and don't need to worry about changes in the object integrity, there is no problem in setting `safe` to be `False`.

An example of loading with `safe` turned to `False` is given below.

In [10]:
mc_tutorial = MotifCompendium.load("tutorial_outputs/tutorial_motif_compendium.mc", safe=False)
mc_tutorial

# 2 - Sorting And Slicing MotifCompendium Objects

MotifCompendium offers a familiar and intuitive Pandas-like syntax for sorting and slicing MotifCompendium objects.

To sort a MotifCompendium, simply, call the `sort()` method with a column you would like to sort on.

In [11]:
mc_tutorial.sort("num_seqlets")

The direction of sorting can be changed by setting the value of the `ascending` argument to True or False. By default, it is `True` and sorts from smallest to largest.

In [12]:
mc_tutorial.sort("num_seqlets", ascending=False)

MotifCompendium objects can be sorted by multiple columns when a list of column names is passed in instead of a single column name. If this is done, the ascending argument can be passed a list of boolean values corresponding to whether or not each column should be sorted in ascending order.

In [13]:
mc_tutorial.sort(["posneg", "num_seqlets"], ascending=[True, False])

While `sort()` returned a sorted MotifCompendium object, notice how the original MotifCompendium did not change.

In [14]:
mc_tutorial

If you'd like, the current MotifCompendium can be sorted in-place by setting the `inplace` argument to `True`.

In [15]:
mc_tutorial.sort(["posneg", "num_seqlets"], ascending=[True, False], inplace=True)
mc_tutorial

New columns can easily be added to MotifCompendium objects using the same column assignment syntax as Pandas. The examples below show how a single value of a list can be assigned to a new MotifCompendium column.

In [16]:
mc_tutorial["test_column_1"] = 1
mc_tutorial["test_column_2"] = list(range(len(mc_tutorial)))
mc_tutorial

MotifCompendium objects can also be indexed by strings corresponding to column names. Doing so will return a `pd.Series` corresponding to that column in the MotifCompendium's metadata.

In [17]:
mc_tutorial["name"]

0      cardiomyocyte-neg.pattern_0
1      cardiomyocyte-neg.pattern_1
2      cardiomyocyte-neg.pattern_2
3      cardiomyocyte-neg.pattern_3
4        endothelial-pos.pattern_0
                  ...
83    cardiomyocyte-pos.pattern_40
84      endothelial-pos.pattern_39
85      endothelial-pos.pattern_40
86      endothelial-pos.pattern_41
87      endothelial-pos.pattern_42
Name: name, Length: 88, dtype: object

MotifCompendium objects can also be indexed by boolean `pd.Series`. Doing so will return a sliced MotifCompendium object corresponding only to motifs for which the indexing `pd.Series` was `True`. This allows for a very flexible syntax for getting MotifCompendium objects corresponding to motifs you are interested in.

In [18]:
mc_ctcf = mc_tutorial[mc_tutorial["annotation"] == "CTCF#1_0"]
mc_ctcf

Here are a few more examples of performing slices in this sort of way.

In [19]:
mc_many_seqlets = mc_tutorial[mc_tutorial["num_seqlets"] >= 10000]
mc_many_seqlets

In [20]:
mc_no_positive_endothelial = mc_tutorial[~((mc_tutorial["posneg"] == "pos") & (mc_tutorial["model"] == "endothelial"))]
mc_no_positive_endothelial

# 3 - Accessing Values Of Other MotifCompendium Attributes

In this section, we will discuss how to interact with the various data and attributes of MotifCompendium objects.

## Motifs

The motifs are the core of any MotifCompendium object. They can be accessed directly with `.motifs`. The motifs are a `np.ndarray` of shape `(N, L, C)` where `N` is the number of motifs, `L` is the length of the motifs, and `C` are the number of "nucleotide channels" in the motif representation.

In [21]:
motifs = mc_tutorial.motifs
print(type(motifs), motifs.shape)

<class 'numpy.ndarray'> (88, 30, 8)

The motifs in MotifCompendium objects can have 4 or 8 channels. Even when motifs are represented as 8 channel motifs internally to MotifCompendium, users may care more about the corresponding 4 channel motifs. No matter if your motifs are 4 or 8 channels, you can always get the 4 channel motif representations using the `get_standard_motif_stack()` method. This is the recommended way to access your motifs.

In [22]:
motifs = mc_tutorial.get_standard_motif_stack()
print(type(motifs), motifs.shape)

<class 'numpy.ndarray'> (88, 30, 4)

The channels in the motif are always arranged in such a way that the motifs can always be reverse-complemented using the same syntax.

In [23]:
motifs = mc_tutorial.get_standard_motif_stack()
motifs_revcomp = utils_motif.reverse_complement(motifs)
print(type(motifs_revcomp), motifs_revcomp.shape)

<class 'numpy.ndarray'> (88, 30, 4)

## Similarity & Alignment

Let's discuss the concepts of similarity and alignment as they are used in MotifCompendium.

**Alignment** refers to the way in which two motifs can be arranged with respect to one another. There are two attributes needed to specify how one motif should be aligned with another motif. First, you must specify if one motif should be reverse complemented to best match the other motif. Once this is done, you may need to specify a horizontal shift needed to best align the two motifs.


For any particular alignment between two motifs, one can compute a measure of how similar those motifs are. In MotifCompendium, we measure this **similarity** as a number between 0 and 1. At a given alignment, a score of 1 can be achieved iff two motifs are exactly equal at that alignment. However, the similarity at each alignment is not meaningful as low similarities can be achieved for every motif pair by simply shifting them until there is no overlap between them. So, for any two motifs, their pairwise similarity is considered to be their maximum similarity across all possible alignments.

The MotifCompendium objects store information about pairwise motif similarity and alignment in the `.similarity`, `.alignment_h`, and `.alignment_rc` attributes. Each one of them is a square `np.ndarray` of shape `(N, N)` where `N` is the number of motifs in the MotifCompendium. Here is a little more information about each of them.

- `.similarity` - `similarity[i, j]` is the similarity between the i<sup>th</sup> and j<sup>th</sup> motifs. This is the maximum similarity between the two motifs across all possible alignments. `similarity` is symmetric. The diagonal of `similarity` is all 1s because each motif has full similarity with itself.
- `.alignment_h` - `alignment_h[i, j]` is an integer representing how many positions to the right the j<sup>th</sup> motif must be shifted (after being reverse complemented, if needed) in order to achieve the best possible alignment with the i<sup>th</sup> motif.
- `.alignment_rc` - `alignment_rc[i, j]` is a boolean representing whether or not the j<sup>th</sup> motif must be reverse complemented in order to achieve the best possible alignment with the i<sup>th</sup> motif.

Here is an example of how one would access the similarity and alignment information between motifs.

In [24]:
print(f"similarity: {mc_tutorial.similarity[0, 1]}")
print(f"horizontal alignment: {mc_tutorial.alignment_h[0, 1]}")
print(f"reverse complement: {mc_tutorial.alignment_rc[0, 1]}")

similarity: 0.6910644173622131
horizontal alignment: 4
reverse complement: False

The above means that the 0<sup>th</sup> and 1<sup>st</sup> motifs have a similarity of 0.691, and that their maximum similarity is achieved when the 1<sup>st</sup> motif is reverse complemented and *then* shifted 4 positions to the right.

And here is an example showing a motif's similarity with itself. Notice how the similarity is 1, the horizontal alignment is 0, and it does not need to be reverse complemented to match with itself.

In [25]:
print(f"similarity: {mc_tutorial.similarity[2, 2]}")
print(f"horizontal alignment: {mc_tutorial.alignment_h[2, 2]}")
print(f"reverse complement: {mc_tutorial.alignment_rc[2, 2]}")

similarity: 1.0
horizontal alignment: 0
reverse complement: False

In almost all cases, you will never need to access alignment information yourself. MotifCompendium will take care of alignment information as needed behind the scenes.

Sometimes, you may want to access similarity information by indexing in a more interpretable manner. The `.get_similarity_slice()` method can help you access slices of the similarity matrix by passing in conditions corresponding to certain motifs.

Let's suppose I wanted to look at the similarity of negative motifs with respect to all other motifs. That can be done by passing in a `pd.Series` of booleans corresponding to all the negative motifs. As shown in the slicing section, this can easily be done in a Pandas-like syntax.

In [26]:
endothelial_motif_similarity_slice = mc_tutorial.get_similarity_slice(mc_tutorial["model"] == "endothelial")
endothelial_motif_similarity_slice

,0,1,2,3,4,5,6,7,8,9,...,78,79,80,81,82,83,84,85,86,87
4,0.002069,0.002909,0.006847,0.023028,1.000000,0.464071,0.627148,0.243060,0.655419,0.459783,...,0.500559,0.233582,0.478073,0.823286,0.594629,0.473325,0.453168,0.866266,0.335923,0.324169
9,0.004936,0.004012,0.007935,0.018227,0.459783,0.997925,0.497928,0.296337,0.583620,1.000000,...,0.315990,0.262084,0.359594,0.397281,0.429860,0.531467,0.447451,0.418498,0.340419,0.322643
13,0.001784,0.002621,0.008329,0.023084,0.634150,0.613345,0.620388,0.163096,0.665269,0.618650,...,0.306175,0.136444,0.352055,0.470664,0.539143,0.416494,0.404661,0.576625,0.297929,0.396823
14,0.003845,0.003338,0.007322,0.022204,0.597372,0.470578,0.994201,0.247427,0.769246,0.460548,...,0.308462,0.219096,0.336547,0.457787,0.855556,0.523977,0.413681,0.621136,0.428505,0.348036
20,0.001768,0.001888,0.004340,0.016386,0.358523,0.366372,0.415788,0.459399,0.500495,0.357574,...,0.438831,0.433410,0.431859,0.601638,0.287275,0.483702,0.330033,0.313800,0.934189,0.412497
22,0.001416,0.001417,0.004263,0.014604,0.453224,0.287744,0.399587,0.290958,0.517635,0.282567,...,0.422882,0.281116,0.305516,0.545374,0.288990,0.669318,0.354409,0.404029,0.434129,0.314682
24,0.001775,0.002560,0.005095,0.015897,0.468890,0.382783,0.540950,0.466590,0.613295,0.372384,...,0.506286,0.449816,0.323483,0.387819,0.391428,0.437592,0.406620,0.414646,0.725500,0.326138
27,0.001867,0.002482,0.006928,0.020314,0.458259,0.350357,0.377406,0.275476,0.495284,0.363467,...,0.418331,0.256496,0.424200,0.391504,0.355906,0.650716,0.438497,0.374957,0.487856,0.621185
29,0.002082,0.002368,0.007245,0.020410,0.798687,0.549569,0.505956,0.293779,0.539790,0.543698,...,0.390912,0.257444,0.434575,0.665136,0.530455,0.414629,0.371065,0.709734,0.321184,0.355829
30,0.001873,0.002151,0.007766,0.019871,0.450903,0.468623,0.342492,0.163767,0.431924,0.458383,...,0.268650,0.168193,0.358884,0.451741,0.356212,0.344400,0.524196,0.410767,0.322886,0.408607
32,0.004410,0.004931,0.006556,0.019356,0.613585,0.352505,0.465772,0.405672,0.516050,0.353286,...,0.345355,0.385065,0.545262,0.494531,0.426292,0.350264,0.561994,0.567133,0.381013,0.336228
34,0.002637,0.002985,0.006078,0.020895,0.856009,0.564511,0.564476,0.336989,0.584116,0.556822,...,0.435449,0.305649,0.454173,0.696962,0.529545,0.430291,0.451032,0.738190,0.500719,0.269766
36,0.001739,0.002307,0.006336,0.017149,0.710473,0.455523,0.448402,0.297620,0.473756,0.464624,...,0.359185,0.283968,0.375791,0.606419,0.426243,0.366666,0.581658,0.609289,0.329829,0.356903
37,0.002261,0.002305,0.004246,0.014298,0.542066,0.323019,0.283732,0.403885,0.365503,0.337129,...,0.475696,0.412438,0.366042,0.568277,0.286442,0.428234,0.519227,0.466035,0.440273,0.403378
38,0.002626,0.003579,0.008421,0.017356,0.726226,0.478032,0.475982,0.268436,0.482253,0.488232,...,0.376754,0.219390,0.482924,0.598471,0.485778,0.354737,0.484142,0.642128,0.302269,0.282288
41,0.001711,0.002503,0.007169,0.017298,0.776952,0.472952,0.476854,0.252369,0.514597,0.467467,...,0.397507,0.225060,0.415594,0.617017,0.446072,0.382967,0.458797,0.712595,0.334440,0.359437
42,0.002322,0.002725,0.005131,0.017946,0.730771,0.344467,0.573628,0.297066,0.484514,0.341691,...,0.393824,0.285076,0.349163,0.624046,0.545794,0.452339,0.525426,0.633863,0.401549,0.302623
43,0.002806,0.003506,0.007373,0.018341,0.761931,0.486212,0.452049,0.273751,0.499349,0.501817,...,0.408226,0.246045,0.497564,0.635657,0.436230,0.375165,0.487736,0.665098,0.340679,0.334654
45,0.001481,0.003403,0.007544,0.016989,0.759991,0.415797,0.587117,0.221919,0.499270,0.418181,...,0.384916,0.216783,0.424019,0.651636,0.544149,0.370599,0.541996,0.752531,0.312658,0.279390
46,0.002257,0.002184,0.005440,0.016746,0.739407,0.350752,0.452079,0.307037,0.472949,0.359516,...,0.386051,0.282972,0.496123,0.644236,0.422046,0.552149,0.456279,0.741987,0.426433,0.426728
47,0.002014,0.002457,0.006765,0.021538,0.954103,0.454883,0.598999,0.259548,0.626263,0.449370,...,0.486193,0.248402,0.515624,0.792819,0.560863,0.461727,0.483000,0.835194,0.346898,0.349520
51,0.001952,0.002649,0.006057,0.020793,0.912210,0.418864,0.574459,0.227416,0.600133,0.413952,...,0.468950,0.217975,0.499950,0.767158,0.543874,0.443725,0.430180,0.790624,0.314671,0.390841
52,0.002284,0.002617,0.003057,0.011960,0.437499,0.350794,0.334307,0.431281,0.442873,0.339864,...,0.385070,0.402400,0.260693,0.402152,0.218374,0.626921,0.332629,0.422815,0.369742,0.344538
53,0.002075,0.002803,0.007669,0.020784,0.405009,0.369832,0.415448,0.275775,0.555942,0.379468,...,0.385271,0.272053,0.315044,0.368327,0.355207,0.364319,0.426195,0.358951,0.358993,0.408642
54,0.001679,0.002727,0.002976,0.011008,0.250356,0.324611,0.241065,0.981827,0.290574,0.330176,...,0.494319,0.922037,0.396437,0.424697,0.196968,0.246885,0.343649,0.247065,0.448116,0.370387
56,0.003461,0.003853,0.008254,0.019859,0.859578,0.465233,0.543072,0.273672,0.569394,0.467183,...,0.430736,0.271739,0.421532,0.709050,0.551022,0.419960,0.498166,0.744151,0.348111,0.319826
58,0.002238,0.002004,0.006167,0.017555,0.384955,0.358621,0.395028,0.324672,0.446676,0.352794,...,0.382908,0.327826,0.843884,0.492067,0.293055,0.478922,0.304172,0.327610,0.681012,0.436234
59,0.001952,0.003451,0.006342,0.020879,0.910510,0.418831,0.566353,0.228504,0.596543,0.414241,...,0.453866,0.223641,0.434199,0.748405,0.567112,0.432209,0.412759,0.797099,0.303544,0.315777
60,0.002161,0.002869,0.005632,0.019102,0.839314,0.385410,0.522389,0.209700,0.552762,0.381641,...,0.436128,0.226393,0.406530,0.712229,0.493032,0.412823,0.385161,0.731316,0.287106,0.349732
62,0.002440,0.003336,0.006775,0.020502,0.423222,0.528547,0.530618,0.390839,0.695622,0.522771,...,0.372785,0.371677,0.342674,0.359656,0.428484,0.565133,0.395949,0.421465,0.372658,0.461175
63,0.002541,0.003377,0.006846,0.020163,0.887144,0.400496,0.549524,0.275649,0.576363,0.396486,...,0.473089,0.260452,0.423478,0.786309,0.515110,0.439607,0.548977,0.762690,0.324071,0.313271
65,0.001810,0.001872,0.005654,0.014049,0.409634,0.285493,0.426108,0.278460,0.405949,0.286194,...,0.384146,0.266917,0.313332,0.514704,0.359779,0.539192,0.505352,0.427276,0.400979,0.311799
70,0.003151,0.003406,0.007963,0.020735,0.568160,0.555254,0.557879,0.172352,0.598700,0.559002,...,0.297513,0.162253,0.391671,0.422297,0.482876,0.379564,0.407934,0.516752,0.269180,0.361337
71,0.001897,0.001935,0.005571,0.014269,0.411895,0.249553,0.342426,0.282417,0.420887,0.247947,...,0.393387,0.272264,0.307229,0.501596,0.345847,0.563152,0.386867,0.409746,0.404321,0.290293
72,0.001658,0.002036,0.004329,0.015238,0.342304,0.326289,0.390830,0.410025,0.470559,0.316846,...,0.421650,0.391100,0.406692,0.558138,0.269159,0.455205,0.314121,0.297924,0.870864,0.378160
73,0.001921,0.002784,0.006571,0.018610,0.592975,0.444094,0.487489,0.275375,0.542989,0.451320,...,0.370502,0.261464,0.382838,0.480350,0.439747,0.370454,0.422230,0.506334,0.345837,0.308102
76,0.002134,0.001688,0.004393,0.014318,0.404944,0.271576,0.354247,0.448737,0.439595,0.282147,...,0.433711,0.437883,0.310129,0.509116,0.273021,0.565580,0.340507,0.384468,0.567133,0.342700
77,0.001636,0.002489,0.009323,0.019968,0.526771,0.550697,0.518212,0.205824,0.559501,0.554984,...,0.269226,0.204932,0.345942,0.400216,0.537310,0.372402,0.397562,0.552299,0.297032,0.400400
81,0.001722,0.001946,0.006195,0.019991,0.823286,0.401757,0.484040,0.369661,0.528043,0.397281,...,0.491829,0.344276,0.422245,1.000000,0.468913,0.470346,0.489156,0.702605,0.591259,0.489079
84,0.001362,0.002221,0.008077,0.014744,0.453168,0.441887,0.433153,0.303209,0.377799,0.447451,...,0.339941,0.266798,0.402265,0.489156,0.531943,0.337227,1.000000,0.431960,0.357233,0.360646
85,0.002862,0.002516,0.006697,0.020219,0.866266,0.410421,0.635967,0.254484,0.577958,0.418498,...,0.423116,0.237135,0.409974,0.702605,0.617502,0.410039,0.431960,1.000000,0.318580,0.282775
86,0.003145,0.003322,0.004858,0.016876,0.335923,0.349381,0.424641,0.424237,0.500038,0.340419,...,0.408792,0.419505,0.476884,0.591259,0.304054,0.484264,0.357233,0.318580,1.000000,0.423439
87,0.002621,0.002305,0.006502,0.018018,0.324169,0.331646,0.340721,0.393149,0.358359,0.322643,...,0.310295,0.371526,0.399259,0.489079,0.335201,0.464766,0.360646,0.282775,0.423439,1.000000

As shown above, `.get_similarity_slice()` can be passed a `pd.Series` of booleans and will return a `pd.DataFrame` where each row corresponds to the selected motifs. The returned `pd.DataFrame` contains one column for each motif in the original MotifCompendium. If you want to look at the similarity as compared to a specific set of motifs instead of with respect to all motifs in the original MotifCompendium, you can do this by passing in a second `pd.Series` of booleans corresponding to the other motifs you are interested in looking at.

In [27]:
endothelial_vs_cardiomyocyte_motif_similarity_slice = mc_tutorial.get_similarity_slice(mc_tutorial["model"] == "endothelial", mc_tutorial["model"] == "cardiomyocyte")
endothelial_vs_cardiomyocyte_motif_similarity_slice

,0,1,2,3,5,6,7,8,10,11,...,67,68,69,74,75,78,79,80,82,83
4,0.002069,0.002909,0.006847,0.023028,0.464071,0.627148,0.243060,0.655419,0.324759,0.578680,...,0.507759,0.434003,0.236193,0.495518,0.517179,0.500559,0.233582,0.478073,0.594629,0.473325
9,0.004936,0.004012,0.007935,0.018227,0.997925,0.497928,0.296337,0.583620,0.421141,0.620049,...,0.544448,0.344086,0.275293,0.320616,0.343382,0.315990,0.262084,0.359594,0.429860,0.531467
13,0.001784,0.002621,0.008329,0.023084,0.613345,0.620388,0.163096,0.665269,0.306061,0.972886,...,0.871789,0.310779,0.261356,0.515977,0.454779,0.306175,0.136444,0.352055,0.539143,0.416494
14,0.003845,0.003338,0.007322,0.022204,0.470578,0.994201,0.247427,0.769246,0.318078,0.578054,...,0.504067,0.405228,0.316907,0.707157,0.385607,0.308462,0.219096,0.336547,0.855556,0.523977
20,0.001768,0.001888,0.004340,0.016386,0.366372,0.415788,0.459399,0.500495,0.511285,0.260759,...,0.226846,0.427449,0.403796,0.285266,0.434901,0.438831,0.433410,0.431859,0.287275,0.483702
22,0.001416,0.001417,0.004263,0.014604,0.287744,0.399587,0.290958,0.517635,0.329325,0.282904,...,0.251827,0.920261,0.311338,0.310034,0.437929,0.422882,0.281116,0.305516,0.288990,0.669318
24,0.001775,0.002560,0.005095,0.015897,0.382783,0.540950,0.466590,0.613295,0.556785,0.410703,...,0.363781,0.386576,0.398590,0.316426,0.468789,0.506286,0.449816,0.323483,0.391428,0.437592
27,0.001867,0.002482,0.006928,0.020314,0.350357,0.377406,0.275476,0.495284,0.288492,0.511058,...,0.447505,0.536767,0.286410,0.316271,0.596592,0.418331,0.256496,0.424200,0.355906,0.650716
29,0.002082,0.002368,0.007245,0.020410,0.549569,0.505956,0.293779,0.539790,0.344091,0.596927,...,0.540545,0.339643,0.271572,0.388369,0.461664,0.390912,0.257444,0.434575,0.530455,0.414629
30,0.001873,0.002151,0.007766,0.019871,0.468623,0.342492,0.163767,0.431924,0.198300,0.532319,...,0.463070,0.305301,0.210938,0.348294,0.566102,0.268650,0.168193,0.358884,0.356212,0.344400
32,0.004410,0.004931,0.006556,0.019356,0.352505,0.465772,0.405672,0.516050,0.384404,0.505380,...,0.454783,0.287929,0.352845,0.504687,0.399217,0.345355,0.385065,0.545262,0.426292,0.350264
34,0.002637,0.002985,0.006078,0.020895,0.564511,0.564476,0.336989,0.584116,0.548214,0.527458,...,0.460403,0.374718,0.315715,0.433370,0.467847,0.435449,0.305649,0.454173,0.529545,0.430291
36,0.001739,0.002307,0.006336,0.017149,0.455523,0.448402,0.297620,0.473756,0.364923,0.441055,...,0.378896,0.316109,0.270596,0.464553,0.530358,0.359185,0.283968,0.375791,0.426243,0.366666
37,0.002261,0.002305,0.004246,0.014298,0.323019,0.283732,0.403885,0.365503,0.420175,0.284394,...,0.246211,0.360137,0.388382,0.321131,0.502856,0.475696,0.412438,0.366042,0.286442,0.428234
38,0.002626,0.003579,0.008421,0.017356,0.478032,0.475982,0.268436,0.482253,0.343944,0.672209,...,0.598790,0.349806,0.274345,0.428070,0.406707,0.376754,0.219390,0.482924,0.485778,0.354737
41,0.001711,0.002503,0.007169,0.017298,0.472952,0.476854,0.252369,0.514597,0.325944,0.585820,...,0.526342,0.327484,0.261996,0.429295,0.417547,0.397507,0.225060,0.415594,0.446072,0.382967
42,0.002322,0.002725,0.005131,0.017946,0.344467,0.573628,0.297066,0.484514,0.336569,0.466325,...,0.404589,0.639391,0.303015,0.532262,0.460576,0.393824,0.285076,0.349163,0.545794,0.452339
43,0.002806,0.003506,0.007373,0.018341,0.486212,0.452049,0.273751,0.499349,0.349157,0.631675,...,0.557951,0.352535,0.271412,0.445489,0.447879,0.408226,0.246045,0.497564,0.436230,0.375165
45,0.001481,0.003403,0.007544,0.016989,0.415797,0.587117,0.221919,0.499270,0.254879,0.615996,...,0.550708,0.355634,0.255696,0.606764,0.451835,0.384916,0.216783,0.424019,0.544149,0.370599
46,0.002257,0.002184,0.005440,0.016746,0.350752,0.452079,0.307037,0.472949,0.361544,0.448563,...,0.390791,0.463473,0.330908,0.435055,0.425557,0.386051,0.282972,0.496123,0.422046,0.552149
47,0.002014,0.002457,0.006765,0.021538,0.454883,0.598999,0.259548,0.626263,0.328388,0.562785,...,0.491946,0.453635,0.251352,0.511488,0.522440,0.486193,0.248402,0.515624,0.560863,0.461727
51,0.001952,0.002649,0.006057,0.020793,0.418864,0.574459,0.227416,0.600133,0.291838,0.523000,...,0.457841,0.454390,0.215189,0.453390,0.488483,0.468950,0.217975,0.499950,0.543874,0.443725
52,0.002284,0.002617,0.003057,0.011960,0.350794,0.334307,0.431281,0.442873,0.338230,0.313280,...,0.271855,0.560280,0.389243,0.255656,0.333853,0.385070,0.402400,0.260693,0.218374,0.626921
53,0.002075,0.002803,0.007669,0.020784,0.369832,0.415448,0.275775,0.555942,0.327649,0.628157,...,0.549624,0.341645,0.260760,0.413540,0.563184,0.385271,0.272053,0.315044,0.355207,0.364319
54,0.001679,0.002727,0.002976,0.011008,0.324611,0.241065,0.981827,0.290574,0.836182,0.184956,...,0.173228,0.296370,0.875853,0.215545,0.324536,0.494319,0.922037,0.396437,0.196968,0.246885
56,0.003461,0.003853,0.008254,0.019859,0.465233,0.543072,0.273672,0.569394,0.327411,0.507041,...,0.441862,0.371861,0.270953,0.442581,0.463620,0.430736,0.271739,0.421532,0.551022,0.419960
58,0.002238,0.002004,0.006167,0.017555,0.358621,0.395028,0.324672,0.446676,0.355839,0.301105,...,0.260573,0.377052,0.297284,0.339811,0.435037,0.382908,0.327826,0.843884,0.293055,0.478922
59,0.001952,0.003451,0.006342,0.020879,0.418831,0.566353,0.228504,0.596543,0.304757,0.534950,...,0.477911,0.394652,0.255014,0.449225,0.476782,0.453866,0.223641,0.434199,0.567112,0.432209
60,0.002161,0.002869,0.005632,0.019102,0.385410,0.522389,0.209700,0.552762,0.269450,0.476736,...,0.417373,0.443606,0.198163,0.419272,0.450609,0.436128,0.226393,0.406530,0.493032,0.412823
62,0.002440,0.003336,0.006775,0.020502,0.528547,0.530618,0.390839,0.695622,0.439626,0.722712,...,0.629823,0.390431,0.338110,0.343872,0.519174,0.372785,0.371677,0.342674,0.428484,0.565133
63,0.002541,0.003377,0.006846,0.020163,0.400496,0.549524,0.275649,0.576363,0.311569,0.495901,...,0.433810,0.414575,0.277089,0.434185,0.499425,0.473089,0.260452,0.423478,0.515110,0.439607
65,0.001810,0.001872,0.005654,0.014049,0.285493,0.426108,0.278460,0.405949,0.293911,0.295229,...,0.262298,0.822567,0.254448,0.442792,0.460916,0.384146,0.266917,0.313332,0.359779,0.539192
70,0.003151,0.003406,0.007963,0.020735,0.555254,0.557879,0.172352,0.598700,0.288305,0.887764,...,0.789022,0.314121,0.234606,0.469422,0.424144,0.297513,0.162253,0.391671,0.482876,0.379564
71,0.001897,0.001935,0.005571,0.014269,0.249553,0.342426,0.282417,0.420887,0.312348,0.285154,...,0.254467,0.838858,0.354980,0.318292,0.412535,0.393387,0.272264,0.307229,0.345847,0.563152
72,0.001658,0.002036,0.004329,0.015238,0.326289,0.390830,0.410025,0.470559,0.479030,0.252355,...,0.238125,0.404552,0.363286,0.260526,0.416608,0.421650,0.391100,0.406692,0.269159,0.455205
73,0.001921,0.002784,0.006571,0.018610,0.444094,0.487489,0.275375,0.542989,0.397407,0.470444,...,0.437878,0.291613,0.327519,0.433530,0.386588,0.370502,0.261464,0.382838,0.439747,0.370454
76,0.002134,0.001688,0.004393,0.014318,0.271576,0.354247,0.448737,0.439595,0.430044,0.261452,...,0.232587,0.798974,0.379127,0.320125,0.394240,0.433711,0.437883,0.310129,0.273021,0.565580
77,0.001636,0.002489,0.009323,0.019968,0.550697,0.518212,0.205824,0.559501,0.328979,0.847062,...,0.759394,0.327188,0.264966,0.510434,0.436666,0.269226,0.204932,0.345942,0.537310,0.372402
81,0.001722,0.001946,0.006195,0.019991,0.401757,0.484040,0.369661,0.528043,0.391804,0.426781,...,0.372773,0.513603,0.357547,0.476258,0.503558,0.491829,0.344276,0.422245,0.468913,0.470346
84,0.001362,0.002221,0.008077,0.014744,0.441887,0.433153,0.303209,0.377799,0.481810,0.379048,...,0.359500,0.389217,0.365538,0.855404,0.738417,0.339941,0.266798,0.402265,0.531943,0.337227
85,0.002862,0.002516,0.006697,0.020219,0.410421,0.635967,0.254484,0.577958,0.281751,0.538605,...,0.473234,0.387545,0.200722,0.549576,0.464557,0.423116,0.237135,0.409974,0.617502,0.410039
86,0.003145,0.003322,0.004858,0.016876,0.349381,0.424641,0.424237,0.500038,0.485769,0.271904,...,0.237394,0.429129,0.381958,0.315195,0.454003,0.408792,0.419505,0.476884,0.304054,0.484264
87,0.002621,0.002305,0.006502,0.018018,0.331646,0.340721,0.393149,0.358359,0.308023,0.467711,...,0.406687,0.406124,0.394260,0.312786,0.521235,0.310295,0.371526,0.399259,0.335201,0.464766

Notice how this has returned a `pd.DataFrame` with the same rows but now with only a subset of the columns corresponding to the cardiomyocyte motifs.

If you ever want to see the rows and columns labeled with the motif names, you can set the `with_names` parameter to be `True`.

In [28]:
endothelial_vs_cardiomyocyte_motif_similarity_slice = mc_tutorial.get_similarity_slice(mc_tutorial["model"] == "endothelial", mc_tutorial["model"] == "cardiomyocyte", with_names=True)
endothelial_vs_cardiomyocyte_motif_similarity_slice

,cardiomyocyte-neg.pattern_0,cardiomyocyte-neg.pattern_1,cardiomyocyte-neg.pattern_2,cardiomyocyte-neg.pattern_3,cardiomyocyte-pos.pattern_0,cardiomyocyte-pos.pattern_1,cardiomyocyte-pos.pattern_2,cardiomyocyte-pos.pattern_3,cardiomyocyte-pos.pattern_4,cardiomyocyte-pos.pattern_5,...,cardiomyocyte-pos.pattern_31,cardiomyocyte-pos.pattern_32,cardiomyocyte-pos.pattern_33,cardiomyocyte-pos.pattern_34,cardiomyocyte-pos.pattern_35,cardiomyocyte-pos.pattern_36,cardiomyocyte-pos.pattern_37,cardiomyocyte-pos.pattern_38,cardiomyocyte-pos.pattern_39,cardiomyocyte-pos.pattern_40
endothelial-pos.pattern_0,0.002069,0.002909,0.006847,0.023028,0.464071,0.627148,0.243060,0.655419,0.324759,0.578680,...,0.507759,0.434003,0.236193,0.495518,0.517179,0.500559,0.233582,0.478073,0.594629,0.473325
endothelial-pos.pattern_1,0.004936,0.004012,0.007935,0.018227,0.997925,0.497928,0.296337,0.583620,0.421141,0.620049,...,0.544448,0.344086,0.275293,0.320616,0.343382,0.315990,0.262084,0.359594,0.429860,0.531467
endothelial-pos.pattern_2,0.001784,0.002621,0.008329,0.023084,0.613345,0.620388,0.163096,0.665269,0.306061,0.972886,...,0.871789,0.310779,0.261356,0.515977,0.454779,0.306175,0.136444,0.352055,0.539143,0.416494
endothelial-pos.pattern_3,0.003845,0.003338,0.007322,0.022204,0.470578,0.994201,0.247427,0.769246,0.318078,0.578054,...,0.504067,0.405228,0.316907,0.707157,0.385607,0.308462,0.219096,0.336547,0.855556,0.523977
endothelial-pos.pattern_4,0.001768,0.001888,0.004340,0.016386,0.366372,0.415788,0.459399,0.500495,0.511285,0.260759,...,0.226846,0.427449,0.403796,0.285266,0.434901,0.438831,0.433410,0.431859,0.287275,0.483702
endothelial-pos.pattern_5,0.001416,0.001417,0.004263,0.014604,0.287744,0.399587,0.290958,0.517635,0.329325,0.282904,...,0.251827,0.920261,0.311338,0.310034,0.437929,0.422882,0.281116,0.305516,0.288990,0.669318
endothelial-pos.pattern_6,0.001775,0.002560,0.005095,0.015897,0.382783,0.540950,0.466590,0.613295,0.556785,0.410703,...,0.363781,0.386576,0.398590,0.316426,0.468789,0.506286,0.449816,0.323483,0.391428,0.437592
endothelial-pos.pattern_7,0.001867,0.002482,0.006928,0.020314,0.350357,0.377406,0.275476,0.495284,0.288492,0.511058,...,0.447505,0.536767,0.286410,0.316271,0.596592,0.418331,0.256496,0.424200,0.355906,0.650716
endothelial-pos.pattern_8,0.002082,0.002368,0.007245,0.020410,0.549569,0.505956,0.293779,0.539790,0.344091,0.596927,...,0.540545,0.339643,0.271572,0.388369,0.461664,0.390912,0.257444,0.434575,0.530455,0.414629
endothelial-pos.pattern_9,0.001873,0.002151,0.007766,0.019871,0.468623,0.342492,0.163767,0.431924,0.198300,0.532319,...,0.463070,0.305301,0.210938,0.348294,0.566102,0.268650,0.168193,0.358884,0.356212,0.344400
endothelial-pos.pattern_10,0.004410,0.004931,0.006556,0.019356,0.352505,0.465772,0.405672,0.516050,0.384404,0.505380,...,0.454783,0.287929,0.352845,0.504687,0.399217,0.345355,0.385065,0.545262,0.426292,0.350264
endothelial-pos.pattern_11,0.002637,0.002985,0.006078,0.020895,0.564511,0.564476,0.336989,0.584116,0.548214,0.527458,...,0.460403,0.374718,0.315715,0.433370,0.467847,0.435449,0.305649,0.454173,0.529545,0.430291
endothelial-pos.pattern_12,0.001739,0.002307,0.006336,0.017149,0.455523,0.448402,0.297620,0.473756,0.364923,0.441055,...,0.378896,0.316109,0.270596,0.464553,0.530358,0.359185,0.283968,0.375791,0.426243,0.366666
endothelial-pos.pattern_13,0.002261,0.002305,0.004246,0.014298,0.323019,0.283732,0.403885,0.365503,0.420175,0.284394,...,0.246211,0.360137,0.388382,0.321131,0.502856,0.475696,0.412438,0.366042,0.286442,0.428234
endothelial-pos.pattern_14,0.002626,0.003579,0.008421,0.017356,0.478032,0.475982,0.268436,0.482253,0.343944,0.672209,...,0.598790,0.349806,0.274345,0.428070,0.406707,0.376754,0.219390,0.482924,0.485778,0.354737
endothelial-pos.pattern_15,0.001711,0.002503,0.007169,0.017298,0.472952,0.476854,0.252369,0.514597,0.325944,0.585820,...,0.526342,0.327484,0.261996,0.429295,0.417547,0.397507,0.225060,0.415594,0.446072,0.382967
endothelial-pos.pattern_16,0.002322,0.002725,0.005131,0.017946,0.344467,0.573628,0.297066,0.484514,0.336569,0.466325,...,0.404589,0.639391,0.303015,0.532262,0.460576,0.393824,0.285076,0.349163,0.545794,0.452339
endothelial-pos.pattern_17,0.002806,0.003506,0.007373,0.018341,0.486212,0.452049,0.273751,0.499349,0.349157,0.631675,...,0.557951,0.352535,0.271412,0.445489,0.447879,0.408226,0.246045,0.497564,0.436230,0.375165
endothelial-pos.pattern_18,0.001481,0.003403,0.007544,0.016989,0.415797,0.587117,0.221919,0.499270,0.254879,0.615996,...,0.550708,0.355634,0.255696,0.606764,0.451835,0.384916,0.216783,0.424019,0.544149,0.370599
endothelial-pos.pattern_19,0.002257,0.002184,0.005440,0.016746,0.350752,0.452079,0.307037,0.472949,0.361544,0.448563,...,0.390791,0.463473,0.330908,0.435055,0.425557,0.386051,0.282972,0.496123,0.422046,0.552149
endothelial-pos.pattern_20,0.002014,0.002457,0.006765,0.021538,0.454883,0.598999,0.259548,0.626263,0.328388,0.562785,...,0.491946,0.453635,0.251352,0.511488,0.522440,0.486193,0.248402,0.515624,0.560863,0.461727
endothelial-pos.pattern_21,0.001952,0.002649,0.006057,0.020793,0.418864,0.574459,0.227416,0.600133,0.291838,0.523000,...,0.457841,0.454390,0.215189,0.453390,0.488483,0.468950,0.217975,0.499950,0.543874,0.443725
endothelial-pos.pattern_22,0.002284,0.002617,0.003057,0.011960,0.350794,0.334307,0.431281,0.442873,0.338230,0.313280,...,0.271855,0.560280,0.389243,0.255656,0.333853,0.385070,0.402400,0.260693,0.218374,0.626921
endothelial-pos.pattern_23,0.002075,0.002803,0.007669,0.020784,0.369832,0.415448,0.275775,0.555942,0.327649,0.628157,...,0.549624,0.341645,0.260760,0.413540,0.563184,0.385271,0.272053,0.315044,0.355207,0.364319
endothelial-pos.pattern_24,0.001679,0.002727,0.002976,0.011008,0.324611,0.241065,0.981827,0.290574,0.836182,0.184956,...,0.173228,0.296370,0.875853,0.215545,0.324536,0.494319,0.922037,0.396437,0.196968,0.246885
endothelial-pos.pattern_25,0.003461,0.003853,0.008254,0.019859,0.465233,0.543072,0.273672,0.569394,0.327411,0.507041,...,0.441862,0.371861,0.270953,0.442581,0.463620,0.430736,0.271739,0.421532,0.551022,0.419960
endothelial-pos.pattern_26,0.002238,0.002004,0.006167,0.017555,0.358621,0.395028,0.324672,0.446676,0.355839,0.301105,...,0.260573,0.377052,0.297284,0.339811,0.435037,0.382908,0.327826,0.843884,0.293055,0.478922
endothelial-pos.pattern_27,0.001952,0.003451,0.006342,0.020879,0.418831,0.566353,0.228504,0.596543,0.304757,0.534950,...,0.477911,0.394652,0.255014,0.449225,0.476782,0.453866,0.223641,0.434199,0.567112,0.432209
endothelial-pos.pattern_28,0.002161,0.002869,0.005632,0.019102,0.385410,0.522389,0.209700,0.552762,0.269450,0.476736,...,0.417373,0.443606,0.198163,0.419272,0.450609,0.436128,0.226393,0.406530,0.493032,0.412823
endothelial-pos.pattern_29,0.002440,0.003336,0.006775,0.020502,0.528547,0.530618,0.390839,0.695622,0.439626,0.722712,...,0.629823,0.390431,0.338110,0.343872,0.519174,0.372785,0.371677,0.342674,0.428484,0.565133
endothelial-pos.pattern_30,0.002541,0.003377,0.006846,0.020163,0.400496,0.549524,0.275649,0.576363,0.311569,0.495901,...,0.433810,0.414575,0.277089,0.434185,0.499425,0.473089,0.260452,0.423478,0.515110,0.439607
endothelial-pos.pattern_31,0.001810,0.001872,0.005654,0.014049,0.285493,0.426108,0.278460,0.405949,0.293911,0.295229,...,0.262298,0.822567,0.254448,0.442792,0.460916,0.384146,0.266917,0.313332,0.359779,0.539192
endothelial-pos.pattern_32,0.003151,0.003406,0.007963,0.020735,0.555254,0.557879,0.172352,0.598700,0.288305,0.887764,...,0.789022,0.314121,0.234606,0.469422,0.424144,0.297513,0.162253,0.391671,0.482876,0.379564
endothelial-pos.pattern_33,0.001897,0.001935,0.005571,0.014269,0.249553,0.342426,0.282417,0.420887,0.312348,0.285154,...,0.254467,0.838858,0.354980,0.318292,0.412535,0.393387,0.272264,0.307229,0.345847,0.563152
endothelial-pos.pattern_34,0.001658,0.002036,0.004329,0.015238,0.326289,0.390830,0.410025,0.470559,0.479030,0.252355,...,0.238125,0.404552,0.363286,0.260526,0.416608,0.421650,0.391100,0.406692,0.269159,0.455205
endothelial-pos.pattern_35,0.001921,0.002784,0.006571,0.018610,0.444094,0.487489,0.275375,0.542989,0.397407,0.470444,...,0.437878,0.291613,0.327519,0.433530,0.386588,0.370502,0.261464,0.382838,0.439747,0.370454
endothelial-pos.pattern_36,0.002134,0.001688,0.004393,0.014318,0.271576,0.354247,0.448737,0.439595,0.430044,0.261452,...,0.232587,0.798974,0.379127,0.320125,0.394240,0.433711,0.437883,0.310129,0.273021,0.565580
endothelial-pos.pattern_37,0.001636,0.002489,0.009323,0.019968,0.550697,0.518212,0.205824,0.559501,0.328979,0.847062,...,0.759394,0.327188,0.264966,0.510434,0.436666,0.269226,0.204932,0.345942,0.537310,0.372402
endothelial-pos.pattern_38,0.001722,0.001946,0.006195,0.019991,0.401757,0.484040,0.369661,0.528043,0.391804,0.426781,...,0.372773,0.513603,0.357547,0.476258,0.503558,0.491829,0.344276,0.422245,0.468913,0.470346
endothelial-pos.pattern_39,0.001362,0.002221,0.008077,0.014744,0.441887,0.433153,0.303209,0.377799,0.481810,0.379048,...,0.359500,0.389217,0.365538,0.855404,0.738417,0.339941,0.266798,0.402265,0.531943,0.337227
endothelial-pos.pattern_40,0.002862,0.002516,0.006697,0.020219,0.410421,0.635967,0.254484,0.577958,0.281751,0.538605,...,0.473234,0.387545,0.200722,0.549576,0.464557,0.423116,0.237135,0.409974,0.617502,0.410039
endothelial-pos.pattern_41,0.003145,0.003322,0.004858,0.016876,0.349381,0.424641,0.424237,0.500038,0.485769,0.271904,...,0.237394,0.429129,0.381958,0.315195,0.454003,0.408792,0.419505,0.476884,0.304054,0.484264
endothelial-pos.pattern_42,0.002621,0.002305,0.006502,0.018018,0.331646,0.340721,0.393149,0.358359,0.308023,0.467711,...,0.406687,0.406124,0.394260,0.312786,0.521235,0.310295,0.371526,0.399259,0.335201,0.464766

And if you want a `np.ndarray` of results, you can use the `pd.DataFrame` `.to_numpy()` method.

In [29]:
endothelial_vs_cardiomyocyte_motif_similarity_slice_np = mc_tutorial.get_similarity_slice(mc_tutorial["model"] == "endothelial", mc_tutorial["model"] == "cardiomyocyte", with_names=True).to_numpy()
print(type(endothelial_vs_cardiomyocyte_motif_similarity_slice_np), endothelial_vs_cardiomyocyte_motif_similarity_slice_np.shape)

<class 'numpy.ndarray'> (43, 45)

## Metadata

MotifCompendium objects maintain metadata tables in the `.metadata` attribute. The metadata serves as a way to flexibly store information about each motif. `.metadata` is a `pd.DataFrame` and can be accessed directly.

In [30]:
metadata = mc_tutorial.metadata
print(type(metadata))
metadata

<class 'pandas.core.frame.DataFrame'>

,name,num_seqlets,model,posneg,avg_dist_from_summit,cluster,annotation,test_column_1,test_column_2
0,cardiomyocyte-neg.pattern_0,55,cardiomyocyte,neg,114.309091,41,NFYrepressive_41,1,0
1,cardiomyocyte-neg.pattern_1,50,cardiomyocyte,neg,81.700000,42,YY1-2repressive_42,1,1
2,cardiomyocyte-neg.pattern_2,46,cardiomyocyte,neg,53.630435,43,ZBT7A.H13CORE.0.P.B_43,1,2
3,cardiomyocyte-neg.pattern_3,22,cardiomyocyte,neg,46.090909,44,ZEB-SNAI_44,1,3
4,endothelial-pos.pattern_0,24805,endothelial,pos,45.475912,45,ETS:ELF-ETV#1_45,1,4
...,...,...,...,...,...,...,...,...,...
83,cardiomyocyte-pos.pattern_40,27,cardiomyocyte,pos,29.444444,39,HD:MEIS-TGIF_39,1,83
84,endothelial-pos.pattern_39,25,endothelial,pos,93.160000,71,HSF1_71,1,84
85,endothelial-pos.pattern_40,23,endothelial,pos,53.347826,73,Unknown_73,1,85
86,endothelial-pos.pattern_41,22,endothelial,pos,43.545455,74,SOX#1_74,1,86
87,endothelial-pos.pattern_42,21,endothelial,pos,37.571429,75,RFX#1_75,1,87

The columns of the metadata can be gotten directly with the `.columns()` method, which returns a list of column names.

In [31]:
mc_tutorial.columns()

['name',
 'num_seqlets',
 'model',
 'posneg',
 'avg_dist_from_summit',
 'cluster',
 'annotation',
 'test_column_1',
 'test_column_2']

As shown above, the best way to get and set columns of the metadata is with the `[]` indexing operator.

In [32]:
mc_tutorial["name"] # Get metadata column value

0      cardiomyocyte-neg.pattern_0
1      cardiomyocyte-neg.pattern_1
2      cardiomyocyte-neg.pattern_2
3      cardiomyocyte-neg.pattern_3
4        endothelial-pos.pattern_0
                  ...
83    cardiomyocyte-pos.pattern_40
84      endothelial-pos.pattern_39
85      endothelial-pos.pattern_40
86      endothelial-pos.pattern_41
87      endothelial-pos.pattern_42
Name: name, Length: 88, dtype: object

In [33]:
mc_tutorial["test_column_3"] = "new test column"
mc_tutorial

The best way to rename columns is with the `.rename_columns()` method, which takes in a dictionary of old column names to new column names.

In [34]:
mc_tutorial.rename_columns({"cluster": "cluster_id", "test_column_1": "1_value"})
mc_tutorial

The best way to delete columns is with the `.delete_column()` method, which can take in either a single column name or a lsit of column names in order to delete them from the metadata.

In [35]:
mc_tutorial.delete_columns("1_value")
mc_tutorial

In [36]:
mc_tutorial.delete_columns(["test_column_2", "test_column_3"])
mc_tutorial

## Images

You may have noticed that when printing out a MotifCompendium object, there is a section at the bottom for images. This is because MotifCompendium objects can also store visual metadata about each motif. For instance, it can store forward/reverse logos for each motif and logos of the closest match in a known database. 

This visual metadata is most naturally populated when performing certain plotting or labeling actions. For instance, when creating a summary table, forward and reverse logos of each motif are generated. When annotating motifs from either an external MotifCompendium or a PFM database, logos of the closest matches are generated.

Image metadata is stored as UTF-8 embeded strings. Unlike the normal metadata, the image metadata cannot be accessed or modified as directly.

In many cases, the image metadata will be populated automatically. One way you can manually add images is by calling the `.add_logos()` method, which takes in a motif stack of shape `(N, L, 4)` and saves the logo of each motif in the provided motif stack in the metadata of the MotifCompendium. The `.add_logo()` method also takes in a name for the saved images.

Below, we will add images for the forward/reverse logos of each motif. Notice how we use the `.get_standard_motif_stack()` method in order to pass 4 channel motifs into `.add_logos()`.

In [37]:
mc_tutorial.add_logos(mc_tutorial.get_standard_motif_stack(), "logo (fwd)")
mc_tutorial.add_logos(utils_motif.reverse_complement(mc_tutorial.get_standard_motif_stack()), "logo (rev)")
mc_tutorial

To get a list of all saved images, use the `.get_saved_images()` method.

In [38]:
mc_tutorial.get_saved_images()

['logo (fwd)', 'logo (rev)']

If you would like to get the UTF-8 embedded image strings of a particular image, you can use the `.get_images()` method and pass it the name of the saved images you want to retrieve. As you can see, these strings are quite arduous to work with so it is not recommended to ever interact with them yourself.

In [39]:
fwd_logo_strings = mc_tutorial.get_images("logo (fwd)")
print(len(fwd_logo_strings), type(fwd_logo_strings))
fwd_logo_strings[0]

88 <class 'list'>

'iVBORw0KGgoAAAANSUhEUgAAAeQAAACuCAYAAADnGn5HAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjAsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvlHJYcgAAAAlwSFlzAAAPYQAAD2EBqD+naQAAK2ZJREFUeJzt3XmcHFW99/FPVfU+07PPZLKTPSSBLGyymyCruIGgIiCKKBdRHzQo9wHuFQEVAfGionARiArK8oCAiOyyKBAjEMKWPZN1kslMJrP2WvX8cTIz3dXdM91dPZke+vd+veaVdHVV95ml+9u/c06d0izLshBCCCHEiNJHugFCCCGEkEAWQgghioIEshBCCFEEJJCFEEKIIiCBLIQQQhQBCWQhhBCiCEggCyGEEEVAAlkIIYQoAhLIQgghRBFwjXQDhBCiqPQ2w7rboX0l9G4DzY3VsBj8Y7GMMoiHoGczAFrHe2BF0TQDxp4MMy4Z4caL0UzLdunMpZdcSKS9GZ/LxKVDR8hDyIS4ZWJa4HPFcekmLj2OzxXDQica19nc4aXHiNBR1k6nv4OQtxdfOIAr7ibYXYFu6XT5ugh7QvS6e3FZBpW9FQR7KvCFyomEawiFqojF/JimG02z8Hg60PUIuh7f1zoLsNA0sCwN0PB42tHdIaJGlIgRIeaKYWJiaRbuuBvd0okaUUzNRLd0DNPAHXPjiXtwmS6MeBCPVY5hedA1nd6oG1wdoIXR9BgeVwxDM9E1E49hYloGcdOgPRqnO67RZQboQSOsW+iWjsfVhd/ScZsaIU+IqB7FNGLolo434sUb9RPQoriNKBou0HQsDWKWBnoUzbTQsMCIAxa6puHSLDRTQzMNoqZGe8dk2ttnEA5XE4v50TSTqqrVuN3dGEZk38/I6v+ZWZYO6Pj9u4hEKtizZ+a+YwOARXX1GtzuroRjzf6/B/Vz1vH7W3D7Wwi7w3TrMXoNiJk6cXTcMR/umIewK0LMiGKYOq64G1/cgzfmoowYfk8v9YEQ5Z4IXlccXbO47s7Xkv72/uOcxbh0k8byHuKWRszU2NFZxvYeHyFPiF5PL73uXmJoRNHwRgK4Y15CrggRI4rLNHDFDfwxD4Goh4BpEI0E2dM2h57eeqLRIPGYj0DZDrzedlxGCDRT/bw19edloYGlvt9d016ivawdAG/Uy7yt8zK+bt484E3MfT+3+o56JrVOStnnsccfT7r9yU98Iu1j1QV6OHhMK7X+Xso8MTrDbpr2VtAbNYhbOmXuKHWBXjQNZtftIW5qRE2d91tqeLFpQsY2HjxmN8dM2sarW8byZnNDyv0RLFoCXbQGWwh5e/D3VuCP+igLlaFjgWbR7esk7A7R5e/AG/VR29FATWctlqXT2jWZaKiaWLQcVziI39+Cx9OBYUT2/U2p126vuxcTwNLx6RGqfbuZVNnJlKoOagMhgp4I4bhBe8hLOGaoV72lATCnvg0LCMVcNLUHWbG9gWMm7aChrAefK0531MV7LTXsDXkJxQzchkmNPwzA2PJu3Ib6fW/rLOfVzRPp6WkkGi0jHvdhmi7c7i5e+ceNST+Xj53wZdQfiI5lga7HcJU3s7ZxLb2e3v7feX1HfcrPNOQOsalhU//7z9SdUynvrqGjZwyhuJ+w6SZuuTC8e/G4u/FYFporTFyPYZoGmqWr9ynThdsEn28PHT3j6I0FCMfdxHFheNv3HQumESGux9ABzdIx4m51rAXBwE5qyqME3RY+A7S4i729PqKWSdyy0DAJuGNoGnh83fveQzQ6e300d3nx6Ba6YaJpFhYQNXUsy8JSu6EbcbA0DM3CADAN4qZGT8RPS8shhEI1RKPlxONeysu34ve3YBghNC2OpoF6f1csS0PToLJiAxWGF5+h49E1LEunM2Jg6VFMy0TXLXyuKABeVwxds7AsjVDMza5QnFA0SCTuJoaBaelorhCGEcawNNDiWLoJmgWmpvLBMjBMA6+nK+PraCiPPfbYkPtkHcjNXc1E4+obDLgD1AZq2ffTGmBZdEe6aettUw+uaYwtH8t77xq8+SZs2wa72yLs7t1FxYTtVFTGKS/TCcV7KfcEmFY7jVp/LZYF8TjMnw+hnr8R37MSV2Q3XmLU1S6AwAQw/KAZEG2HeJiOnp10dGxQbdL9NM66EFfnatjxNHSugUgrVC2A6gXgqQbdA+EWiHVBpB26N4FlguGDWd+G4Iykby0WA5c7+fvt7lJvJH1fhgEuV+qPpa23jZpAbdK2pj2bGBsci8fwZPPjz8rbTU3c+fTL7NgB8XCAacG5jBvjIVgZx+sz97XTYmP7Bja0bcSyYHrNTM455hh2hZu48+lX2Ls7QDwUYEHdkUybEKSqysLnH/g+V+1axcrmt7AsjUpvNV9ffBpuynntNdi1C0Ihtd+iRTBmDJSXg64P/Iz6freRCNTUgFd/g9XrH2RX2we4zAiVNXNxBafhcpdjoeOKdxEL7aa1p5WdXc34XB5m185ixqwvsa25kRdegE2boK1N/Y6OOALGj4dgENxu9TsB9Zx9zztunNr3mWegqUkdG4nA0UdDYyNU+3cRYAu9runE9Ur6XiGmCRMnwrXvfZH7Vt0HwMSKiWy+bHPG34n7WjcxMwbAd4/8LjeddFPqTmleR2lF2qF1OfRshehe0N1QNhlcQTC8YMUTjrXU37NlQv1R6u86nT0r4ZmjIN4Dmg6H/GLQKm9d2zqe3/g8r219DZ/Lx7ENs+ja8Rzvxj1MH/9RlkxZwpz6Of3790R7WPr0Un694tcAHDf5OI6bdFzK477b8i6PfPAIAJ+e/WnuOP0O6kMb4bUvQ+dq9b3VHQ3zr4fARHBXQWQP7P6H+h67N0G0U70fNCymc9yn+NM7f+KPb99Dd88uDm2cx7zamYwpq0Pb9zNqD7WzrWMbr2z9J7rm5qQZH+eziy7h0TV/5Yrnruhv24ZvbaC+LDVUAY6/53je2PEGAEumLOHRzz9KT7SH6166jptfvZlIPIKhGVy06CKmVk8lHA/zy+W/ZGf3TgBOmnYSvzj1F8ysnQndW+Cda6DjAwjtBG8dTDlf/WsEwAzD7tfUz2LX31Wl7vJDxRw48nfpf2G2vy3LtFL+3AA6w52sbVvL2ta1rN+znuauZqp8VcysnUlrTyvr2tYR9AaZUDGBmbUzmVk7k4kVE9HSPVi2LJNtby+ns3kj0a7dmNFeerTJBKqqcfv8uFxgmB1omoUvtArD7CSOF9OoZsIJ38rq+037WjJj6u+mezNE2sCMQsVscFeq1xEahHapfSOt6uesGeCthwmfzP/7zULWgbyzayd/ePsPLFu5jHd2vcPCsQuZXjOdj8/4OC7dxetbX2fFjhW81fwWQU+Qcw8+lwsWXMC8hnm8/jq8+SZs3QodHeDxqLCtroZAYF+G7hvNtiz1ZZpqn0BlDw+99xB3v3U3L256kclVk5laPZWz55xNuaecFza9wKtbX2Vd2zoayxu5YP4FXLDgAqZUT2HTJnjkEXj3XWhuho72GLNnRZk8yaSqysTQTXRdVdQWBtG4i0jMzamnahx4YLqfVpZvnGl/0g6OzUE4FuYva/7CH1b9gb+u/St+l58vzPsCh40/jHtX3csLG19gbHAs58w7h/Pmn8fBYw7uP3ZN6xque+k67lt1H3ErTq2/lksPv5SGsgZe2/oa9666F9MyqQvUsfTIpXzj8G9Q7ikvyPe7N7SXVza/wktNL/Fuy7vMb1hIVfcRvLZ2DTva2zh4wnROXDCH0w9dgNc1yIcYJz/ncBu8/X9h/W/BioHuhQmfgQU/UcG3z4WPXshdb90FQH2gnl2X70r7cKZlYvzQ6L995bFXct2S6wrbZifHRzvhbwuga0Py9iXPw5jFQx/f8QE8txhCzeAqh0W3wLSvpt31qXVP8ZXHvsL2zu14DS83n3Qzp844lTd2vMHX//J12nrbqPBW8D+n/A8XLLgg+eB4SL1BhnerDyVjT0i+f8uj6sOJ4QNXGVQd3P8BJBKP8OcP/sydb9zJsxueZUHjAs47+Dye2/gcT657krn1c/nqoq9y7sHnUuOvAeCBdx/gcw99rv/h3/z6myxoXJD2+xr/s/Fs79wOwAULLuDuT93df9/q3av55pPf5JkNzxBwB7jsI5fx0HsPsbp1NRMrJvKzk3/GZ+d8NvkB974HHatVIEf3gjs4EMigggEY+MAVh7ojwdeQ+neQLctydmyeYuF2mt65BbNrA57YXgKeIFUTTsVyV6mCCxOtexOxeJRN7ZuImVF0y6Ru7HFUTTwdrzvDh8xhbPNwyzqQE72x4w3ueeseVmxfQWN5Iw1lDazcuZKJFRM5f/75nDL9FFz6EMPTebyJbNizgXveuodXt75K0BOksbyRNa1rGBccx/nzz2fJlCXo2sA8tauvhrvvVpU5wJw5cN11MHMmNDSA16uqKMuCcBi6u6G9XVVJdfX5/YGGoyG8Lq/6FNb2L2hfBR3vqxdYrBtiPWBFAV29abgrwFsLvrEw8UyoTPdJIEdmFPaspLv5eZp3voYR68YV78WwIrhcfuqCk9C8teBrVEFTfywExvUfvrZ1Lde/fD33rboPv9vPYeMO44VNL/QH8SWHXUKZpyz9c3dthPa31ZtK9wb1pm/FVI+Eq1y9uQQmQnAmVC8ET2X/obt3w333wXPPwUsvqd+FXXU1HHccfO97cNRRaZ4/33CKR+CFE6DlldT7vPWw5DmoOgiAbzzxDW5bcRsAQU+Qjv/sSPuQPdEeyn408HO6dvG1XHXcVYVrs9Pj198Fyy9M3V45D059e/A36d5m+NtCFcaJDrsDpl+U9pC23jYueeIS7n/3fjQ0zpxzJo+vfpxwPMzxk49n2aeXMblqctpjk+T5/bZ0t/DCSxHu/30FG9e56Wg3qCh3M3MmLFkCZ52l/r5e3fIqR9018Mf1xDlPcNqM01IeL27G8V7nJW6pobOrj7uaHy7+Ycp+T617ipNnnJK0rTvclfk1ZJfN99u5Dp45GsL7PhxWzoWj74fyGWB41Otw274u0x1/Ux9uAPzj4Yg7s2vHMIibcZZvW87T65/mqfVPsXzbcmbVzeLU6aeypWMLT69/GkMz+NjUj3HStJM4adpJTKhQwy9/WfMXlj69lNWtq6kL1Kn7ghP6q/auSBdNe5t4Ys0TWFh8bu7nuOFjN2T3NzZC8grkwjzz/qkYAfbuVRVySwu0tqruyWhU/RuPq25Ntxv8ftXVuXAh3LX6p3z/2e8DUO2rZuXFK5lYOTHlsb/15Lf4xfJfADC1eipvfO0NKltfgeVfHXizqj8OZl+musx99fu61jpg14vwr68NPNggb2ZZMaPw5uWw4U4V/poOY06EhuP3dfNVqJ/7npWw6uqB4xb+TLXPLpff0bYn4O2roP0tdVv3qC7G4Azw1Ki2dG+Epj8OHHPQNTDvvwC45x647LL0IZzOlVeqD1eO2pxoxTdh7S8z3++tgxNfg+A0lj69lJtfvRkAt+4mcnUk7SFtvW3U/nRgqOKmE2/iu0d9t3Btdnr88yfCzmfT33fsn2HCpzIf+/ZV8O71qduNAHz8fShLHSvv88LGF1g8dUnSNtOMJ32YHlQe3++yZfDzn8Nbb2Xep6xM/U2d+eUtTPr5QPvvOP0OLjok9XW5vXM74382vv/27affztcO+VrKfvm2OedjuzdD2wroblLDcWZEfeh2VwDavupazbdRwxtxGHsqlE/Jvi3DrCvSRUd44AOuhsaY8jEZ/zai8Si3/es2rnnxGvaE9nDkhCP51Wm/YsX2FVzx3BW09bZx+PjDueXkWzhqYrpP8MWlJGZZV1aqr1mzsj/m8trLeWXzKzy+5nH2hPaw4PYFVHgrUvZram8CwGt4efCsB6n0VcJ7P06uHOb9NzQmvAFtfxJa901cmp3wBl010H2cl9e/CpsSxpIO/TVMT3iD2PIwND8HoRZnz2O39TF45Qz1Agdo+Cgc+7AaqwfVFRxpU12jiYG8z+23w8UXJ2875BC48EI4+WQYO1b1YDQ1wT//CQ8+mH8PW1pdm2DdbwbfJ7wbXjsPTngZn2ugqyxqRrEsK+1YWigWSrqdeNyI622GXS9kvn/9nZkDOdYLazP8vOI9sOq/4SN3p78fWDwltTs86zDOkWXBpZfCbbcNvW93Nzz8MFz6rbEYmtFf+fZ1SdvZt/dVbgWXbXiXTRr0g9BoUO4pzzwMlobbcPPtj3yb8+afx49e/hFrWtfwgxd/gGVZHDPpGM6eczbnHHSOs7Hu/agkAjkfmqax7NPLWHTHIja1b6Ktt435Y+bzlYVfAWBX9y6WPr0Ua98MwJ+f8nMWjV2kDj7+CXjnB6qLqGsjvHQ6jDtNBa5vDBhlqrs2HlITU0LN+8aCjnDWaDM5AFIm8pRPp3/G4uSBMTKq5jt73jW/GAhjUJVvXxgDrPs1vPcT9X9XwotN99LZCVfZenHPOgv++MeBCVmgei+qqtS8gv/4D+jtddbkJB/cqLrVh7L7VVh3G36XP2lzKBbC7/an7G4P5HT7jJjNDyT/zuyan1IfpLw1qfdt+r2a7JJJ030w/8fgb3TWxmzfRNPtty/EbrwxcxjX1qq5Knv2JG936S7GlI/pD9xtndvSHr+tI3n7sAWyGFKNvyb9hMlRRgJ5ENX+ah747AMcc/cxROIRXtn8CjeeeCOHjDuE0+87vT+MzznoHC4+NKHE81SqCS6LblFjxh2rIbRD/T/eMzCjVfdBcDrUHqG6lJ064h4VeJt+r7qvX79QfSioP1aNFbsrVddrrEd1aXVvUtXyxDOdPe/405O7PjfcBfXHqO8RYO6V6iuNW69XY8d9XC646abkME7HX6hsi3ao9marcz0+V/LvKttALqoKufmZwe83o7DloeQelj5bHhri2Ais/RUcfG3+7YO0leGWLfD3v6uekpYWVdV6vWpOyOzZcOSRaqa9DmzYoOaRJNI0+OIX1ZDH7Nlq286dqjK+4YaB/SZUTBgykPdbhSxKxv4J5Gw+6Q7yKXckHTb+MG4+6Wa++eQ3iZpRvvjwF7lo0UU8sfYJAA6sO5A7Tr8j8wO4AlCzEFg4/I11+eGI38Kin0Pbv9UpMt0b1L87n1PjyuiqTe5KNb5Uc6jz5531bYiH4d3rINYJG5epyVFjT1WnE3hqQDfU8/fuUKehda6DE1/h9deTH+qww2DS/ux12/qo6qnIgT187cGbabu9sh5Re/499D5N96UGcjwCLf8Y+th1v4G5V6sJRQ7F43DnneqD2rp1Q+//iU/AY4/B/fereSKJbroJvvOd5G1jxqhely99Cf70J7VtQsUElm9bDmTXZR1wB/pnaQuRr/0TyEUQrE5cevilvLz5ZR549wFWt65m6TNLAfUifPCsB7OfLbm/uIMw5qPqa3+Z8z2YeSk0P6tmWXeuhT1vqvMlzQhoLvVBwFOrziOfqE73iNl6ij2FOy07O9ufyPkQe6WbbSAXTYXcs019MBpKy8sQblVnAfRpfV318AwlvFt1e49Pv8hJtjo74cwz1TnjiRob1fyCqVNVt3NzM7zxBvz739Czr3kPP5x8zKGHqomDmQQC8BU1IsWE4EC1u7Z1LRf/5eKU/V/ZPDAjf3xwfMr9QuRKuqyzdOcn7mRy5eT+RR5ALQQwt2HuCLaqyLgC6sT5HE6enzMHnnxy4PaKFWqmdVVVwVuXXsvLOR+Sbgw5nXAsnHxcsYwht63Ibj/LVB+wEucb7Hw+++fZ8rDjQL722uQw9nrVJMDzz0/fqdbcDK++qiYArrB9m2edlf2wdOIZFd3Rbm7/9+1Z7y9EviSQsxT0BvnpiT8d6WYMnxEaVrjsMvjVr9QKX6DGBH/yE/U17DrXQW+a7khvvVqtKh6C9f+rZognGPUVclsW3dV9dj6fHMiDzcy2i7Znv28aTU1w663J2666SnUtZ9LYCJ/5jDrNye7EE7N/7lzHg2X8WBSCXO1JjKjx4+Hb307edsMNcMEFauKOObB8NtGoqn6+8x01FuhYuurYFYST/wUH/UCt0LU4dfLTqB9DzrZChuRQtczcjnXokUfU6W59NA0uyfLaDa1pJoEfdFD2z51zIAclkIVzUiELZQTH+X/0I1Uh33rrQDOWLVNflZVq0k04DNu3q1AGNUvWsfZ3UrfZlslMN/t91FfI7SvzO65r/b6JgftHW3LHBH6/Wv88G52dybe9XjWDP1tSIYuRIBWyGHG6rlZRWr4cvvxlmJyQh3v3wpo1qvuyL4wPOECtpuZY79bk2946mJZhpaUEozqQo13pu+mz0f52YdsyBPts+54eWLs2u2PLbPMsw+Hk3pahjA+ORyP7xSQkkEUhSIUsisahh8Jd+04J3rBBBXRbm6qeAwGYMEF1OyYGtiM9W5JvTzgDhlqDnewndRXlwiBdWZw3lEnHB4VrRxY+/3k1Zrxz58C2669Xy6wOpbY2ddv778PcLOdgug03DWUN/VdlGooEsigECWRRlKZOVV/DqsdWITeekH4/m1FdIXdmWWKmY78q1DArL4drrkleVnXZMrVozPe+l7oUblcXPPWUurrbF76Q+nhPP519IIMKWQlksT9Jl7UoTWY89VzcmsOzOnRUT+pyEqr7OZABvv51Fcp6wjvVXXepVbamToUTToDFi9Xpc9XV8NnPqiuFzZiROonrkUdye+7EU5lcuou6QF3/V8Ad6L/P5/JlvF6yELmQQBalKdScvH61uwrKD8jq0Gwr5HB8YIqwoRm4DXeurSy83vTLQGale2Ph2pGD//ovePtttWjHlIQLE23cCM8/r5bSfP99tchMIKCGPgDOOCP5cV5+WV2ONZNYLHkxkcSZ09NrptNyeUv/18WHDJTtsiiIKBTpshalyT5+7B+b9aH5jCEXRXc15D+hy4ymdvH3mXS2Wop1w12DX7DCgblz4be/Vf/fvDl5LWuPR83EnzULDj54YLW3z31OLSySOJnra1+DVavg8svVVcRAXajkiSfUpRcrKgaCPLEb2r585vaugdvSXS0KRQJZlCZ7uOQQyPmMIRdNIPfkWSF3b04ftgecC0f+Xv2/fCqs/M/825alSZOyW+/8wAPh+9+HH/94YFssBrfcohaj6Vt2c/PmgYVpjj12YN/EoO0Id9Ad6e5fJjcxoCWQRaFIl7UoTfYK2Zf9pQLdhhtDG7gcVTaBXBQzrCH/CjnT+PGcKwb+P+v/gF4E3fIJrrkGzj47dXskAh98oE6pC6X/9aUEbWIISyCL4SCBLEqTfSzVHsitK9Q1nNfY1m7s2z2h4h01FbJlqcuApqO71QVAMrGfsw3q+t6VCdOWDd/gjzEC3G51be0bbxy6qna5YMmSgduDBfKOzh0Z9xMiX8X16hFif4l1Jd+2d1nv/seg3a9+t5/uqFq1KqsKuRhmWId2qbFgO1e5Wi7UVQHPHpN+8lakPXXb5C8WvInDQddh6VK1bvpjj6lLOa5Zo5bXLCuDmTNVEJ97bvI57vag7bsu8t7Q3v7ffbr9hMiXBLIoTXHbhXJ9Y3I6PLHiTZxNnajoKuRM3dXzfqCuWw0w/0fwzzQn8Ub3pm4bd2rBmrY/GIa68MRnPpPd/l6Xl/pAPS09LcBAhWyf4DWxQq70JApDuqxFaTJtgewKpN8vg8SKd9SMIWc65WnCpxL+fwZoad4W7BWy7hkI8Q+xdDOt+yrldPsI4YQEsihN9kDWcpuMlM0YcmLlXBQVcijNqlPl0yA4feC24YF0azjbK+SKOUU3gWs4pAvkxArZY3hoKGvY7+0SH04SyKI02QM5x3AZlZO6oh2p28aekuWx7cm3q+c7bs5oMFQgjwuOQ8vmWuJCZEHGkEVpSlylCyDhNKZsJHZBP7vhWWb9clbKPk3tTQP7F8OkLvtENoDGk7I7NmKrkMumpN/vQyYxkPu6quWUJzFcJJBFabIHcI4rTCVWvN3Rbta0rsl6/xGTLpCrF2R3rL1CLstiZY4PgcTA7TvVSQJZDBfpshalSfck3053OtAgcq14i6JCjnYm3zZ8EMhyhrB9DDnb40a5xMDtjfWyp3dPciAHJZBF4UiFLEqT7k2+bdkCuf4YmH9D6nE16soFuVa8RVkhl0+DbMc/7bOsA6VRIdtPadreuT0pkBOvCCWEUxLIojTZK+S4bWJWzSHqK4NcT2MqitOe7IEcnJH9sfYJYf7slxodzdItDrKjS1bpEsNDuqxFaTJsgZzulKBB+IwPQYVcNjW746JdtklwGriCBWtWMfO7/dT4a/pvr2xeSSRhURkJZFFIEsiiNBm2hUB6M6zxnEHOFXIxjCGnLBeaZZVrHz92lWff1f0hkBi6K3asyHhfP01L/cpnH1FyJJBFafKPS76dYyCPyjFk+6SubK9wZZ9h7S6N6rhPUiBvHwhkl+6isbw0uu7F/iGBLEqTfZZwpqsgZZDzLOtiHEPOdv1u+znIJdJd3SdxJvWGPQOXoRxbPhY93TKjQuRJ/ppEabIHcilUyPkGsr3LuoQr5Gy2C5EvCWRRmlICOcOVkDIoqUC2n/JUYhVyplOb5JQnUWhy2pMYvbKZCJNpn3hMrdbVt0JXdC90N0HZ5PT724y6SV1mLPXULk9N+n3thqqQzTjEe9Mfm+1kpXT7WVZ2xw6zjBWyLAoiCkwqZFGadAP8Y5O37X518GMSAmLUVcj26lhzpZ76le2x7ork29sfh4eC6itTMI9i0mUt9hcJZFG6/LY31J3PD77/xt+papBROKnLHqq5XP/ZfiGOEuuyzjmQLSu/L1HyJJBF6bKPI2/5fxCPpN832gkrr+i/OeorZPt52IOxX3ijxCZ1lXvKqfRWpmyXClkUmgSyKF32QI60wYa70u+7/CIINfffHHVjyFF7hVyW/bFmaVfIkD58JZBFoUkgi9JVMTN121uXQ9fG5G0rr4TN9ydtGn0Vsv1KTw4qZMObfr8PMfuMakMzGBccl2FvIfIjs6xF6ao/LnVbrAue+yjMuUItEbnuN7D7nym7ldYYsi2Q7deSLgH2GdWN5Y0Yeun9HMTwkkAWpavyQPA2QHhX8vaezbDikkEPHXUVspMuawlkZtbOpC5Q1397XsO8EWyN+LCSQBalreF42PJgzoeNujFkR5O6bGPIuSwX+SGZPXz50Zdz+dGXj3QzxIecjCGL0Svf00sSQ2LsKXk9dS4Vr4aG1zXC464pXda2CjnaAXvfU192UiELsV9IIIvSNvEM0LNcICNBLoE84mEMqQt22CvkHX+Dv85VX/YAlkAWYr+QQBalzVMFU87P+bBcuqBHvLsaUkPVyRiyvG0IMSzklSXEnP9US0kOxVvXP37qdXnRyG6d5hGf0AVpAjmHMWS7bNenFkLkRAJZiPKpMO3CIXbS4CO/TwqjbIN2xE95gjTnEucQyPYu6pSKWQhRCBLIQgAs+h+oOzL9fZoOh9wK45IngGUbyMVRIZvJt3PpspZAFmK/kEAWAtTqU8c+CpM+D4ld0eXT4dg/w8xLUw7JtvItyjFk3Z39sRLIQuwXch6yEH189XD0H+GgH8DedyAwCaoXgp7+ZTKqK+RcziVOCWQz/X5CCEckkIWwq5ilvoaQWPkeNu4wPjnrk/237111Lx/s/kDtV4xjyLl0jtknvNkfq/IgWPiz1OOC07N/DiGEBLIQ+UqsfOc1zOOq467qv/2PLf/oD+SiqJApZIVsC+TgNJh9WX7NEkL0kzFkIfKUWPmGYqGk+xJvF+UYspNANjNcM1oI4YgEshB5Sqx8BwvkoqiQU8Z9c3jp28fQo53p9xNCOCKBLESeRlcgF7BCjnY4b48QIoUEshB5SuyKHn1d1jmsR22f1BWTClmI4SCBLESeRleF7GBSl2H7QCEVshDDQgJZiDwNViGHY+GB/YrhtCe7XK5T7KlKvi1jyEIMCwlkIfI0qirklC7qHBb3cFcm345JhSzEcJBAFiJPiZVvOB5Ouq/oxpCdrLaVUiFLIAsxHCSQhcjTYBVyYkAXR4Vse6nnEsjuquTb0mUtxLCQQBYiT5nGkCPxCGZC4BXFGHIhu6ylQhZiWEggC5GnTBWyvVouzgo5hys22bus4z1gyhWfhCg0WctaiDwljSEnzKpO/D+MkjFk/zgYd1rqcdWLwB1UxyeGeKwzNaiFEI5IIAuRp8TKN27FicajuA13kVbIQwRy/TFw/BOZj3dXQGTPwO3QLglkIQpMuqyFyJO98u0LYnsgF8UYsv2lnus1je0Tu7qbHLVGCJFKAlmIPNkr30yBXBQVsu7wik32arhHAlmIQpNAFiJP9qDtO9WpKAPZ/lKPd+d2uH2mdTYVcq5VuBAlTgJZiDzZu6IzdlkX46SuWI6BbK+QuzYOvn/PNunWFiJHEshC5ClTl7V91a6iqJCdBrJ9DLn97cH33/pnqZCFyJEEshB5GlWTulICuSe34+1d1h3vQzyUfl+ArY/k9vhCCAlkIfI1qiZ12S+hmOsYsr3L2opB+zvp9w23wq4Xc3t8IYQEshD5GlVjyO5g8m2nXdYAO59Lv+/6/1WBLYTIiQSyEHnKpkL2GB40TSvME2pa+q9s9nOVJ++Ta5e1pzJ128bfpW4zo7Dml7k9thACkEAWIm/2yrdvycyiu/QipAZyrl3WvsbUbR3vQeuK5G2b/gC923J7bCEEIIEsRN6yqZCLYvwYnHdZl09Nv31tQjXcuR7e+n5ujyuE6CdrWQuRJ03T8BrelAVBEi8uURQzrCFNl3WOgVx2gLpilP1Upo3L1AzsmsPgraUQbnHUTCFKmQSyEA74XL6UQC7KCtnpGLLhVVeE6tmaet+aW/NvlxCin3RZC+FAumsiF2Ug27uscx1DBiifVpi2CCHSkkAWwoHELul0gVy8k7pCua+kVZZhHFkIURASyEI4MGoqZFcZYDtFKtdu60wTu4QQBSGBLIQDiRVwfyAnLClZNJO6NB1cgeRt4d25PUbFzMK1RwiRQgJZCAcSK+C+yV2Js6yLpkKG1G7rUHNux1fNL1xbhBApJJCFcGDUjCFDaiD37sjt+OCMfV3fQojhIIEshAOjZgwZwGWbaZ1rhazpUL2wcO0RQiSRQBbCgbRjyMVaIbvzqJBN20UiGhYXrj1CiCQSyEI4MLoqZPsY8hCB3L0FQjuTtzV+rLBtEkL0k0AWwoEhK+RimWUNqV3WnesG33/X3wEreVvdkdmNI2s6uCtyaZ0QJU8CWQgH0lXIfbOt7fePOHuF3Ll68P13vZi6TXdD/XFDP1fjyeCrz75tQggJZCGcGFVd1unGkKOdmfff9ff028d/cujnmn5x1s0SQigSyEI4kNglbb/IBBTZpC57lzVA55r0+3Zvga716e+bcj54ajM/T9kUGPfx3NsnRImTQBbCgVFVIdu7rAHaVqTfd8uDgzxOAGZ+I/P9i24B3citbUIICWQhnNivk7osK/8vSO2yBtj+1/TP1XTf4G2Z+U1wV6VuH/8JmPCpnL4tIYQigSyEA/YK2bIsIvFI2vtHnCvNrOedz0HCJDQAOtdC278HfyxvHZzwAngTJm7VHwsf+Z3zdgpRolwj3QAhRjP70plhW7gV1RiyvzF1W6xbzaYee9LAtnW3Z/d41QvgxH/C5vvVpRknfx40bcjDhBDpSSAL4YC9Qk7srrbfP+L849Nvb/rjQCB3rIZ1v8n+MYPTYe6VztsmhJBAFsKJxAo4Eo/QG+1Nvr+YFgYJZAjkjffAmMVQfwy8eJqqmoUQ+50EshAO2Cvg9lD7oPePKE81GH6I96be99qX9n97hBBJZFKXEA7YK+C94b3J9xfTGDJk7rYWQow4CWQhHBhVFTJAYMJIt0AIkYEEshAO2AN3b2jvoPePOKmQhShaEshCOGDvkrZXyEU1qQsyT+wSQow4CWQhHJAuayFEoUggC+GAvQJODGSX7sKlF9mJDGVTR7oFQogMJJCFcGCwCrnoqmOA4IyRboEQIgMJZCEcSBlDDrdnvK8olE8FrciqdiEEIIEshCOGbiR1SyfOsi7KCll3qVAWQhQdCWQhHEqshBMXBkk7w1rTUr+y2aeQF22oXli4xxJCFIwEshAOJVbCRT+GDFBz2Ei3QAiRhgSyEA4lVsKJgVyUY8gAtYePdAuEEGlIIAvh0OirkA8BzchuX6NIvwchPoQkkIVwKLES7on2DGwvtlW6+rgCUDl36P2q5oO3bvjbI4QAJJCFcCxTJVy0FTJkN4488Yzhb4cQop8EshAOjcpAHnfq0PtMkEAWYn+SQBbCoUxd00U7qQtg3Ongrsp8f+VcqJq335ojhJBAFsKxUVkhG16YdHbm+2dfvv/aIoQAJJCFcCxTJVzUFTLAlPPSbw9MggPO2b9tEUJIIAvh1KiskAHqj4Gxp6RuP/ha0N37vz1ClDgJZCEcylghF+tpT4mO+hNUzB64feD3YMr5I9ceIUqYXPZFCIdGbYUM4KmEjz4NTfdC1cEw7rSRbpEQJUsCWQiHRuUs60RlE2HOFSPdCiFKnnRZC+HQqK6QhRBFQwJZCIdG9RiyEKJoSCAL4ZBUyEKIQpBAFsIhCWQhRCFIIAvh0Kif1CWEKAoSyEI4JBWyEKIQJJCFcEgmdQkhCkECWQiHpEIWQhSCBLIQDskYshCiECSQhXBIKmQhRCFIIAvhkIwhCyEKQQJZCIekQhZCFIIEshAOpauEdU3HY3hGoDVCiNFKrvYkhEPpKuGM1bFlDXNrhBCjlVTIQjiUUyALIUQGEshCOOQxPOha8ktJTnkSQuRKAlmIArBXxFIhCyFyJYEsRAHYK2I55UkIkSsJZCEKQCpkIYRTEshCFIC9IpYxZCFEriSQhSgAqZCFEE5JIAtRADKGLIRwSgJZiAKQClkI4ZQEshAFIGPIQginJJCFKACpkIUQTkkgC1EA9opYAlkIkSvNsmS1eyGEEGKkSYUshBBCFAEJZCGEEKIISCALIYQQRUACWQghhCgCEshCCCFEEZBAFkIIIYqABLIQQghRBCSQhRBCiCIggSyEEEIUgf8PK4HjJV2l6lEAAAAASUVORK5CYII='

The best way to rename saved images is with the `.rename_images()` method, which takes in a dictionary of old saved image names to new saved image names.

In [40]:
mc_tutorial.rename_images({"logo (fwd)": "logo (forward)"})
mc_tutorial

UTF-8 embedded images can take up quite a bit of memory so it is recommended to delete images that you won't regularly use or need. The best way to delete saved images is with the `.delete_images()` method, which can take as input a saved image or a list of saved images to delete.

In [41]:
mc_tutorial.delete_images(["logo (forward)", "logo (rev)"])
mc_tutorial

## Miscellaneous

The length of a MotifCompendium object will return the number of motifs in the MotifCompendium.

In [42]:
len(mc_tutorial)

88

MotifCompendum objects can be printed directly.

In [43]:
print(mc_tutorial)

MotifCompendium with 88 motifs.
--- Motifs = (88, 30, 8) ---

--- Metadata ---
                            name  num_seqlets          model posneg  \
0    cardiomyocyte-neg.pattern_0           55  cardiomyocyte    neg
1    cardiomyocyte-neg.pattern_1           50  cardiomyocyte    neg
2    cardiomyocyte-neg.pattern_2           46  cardiomyocyte    neg
3    cardiomyocyte-neg.pattern_3           22  cardiomyocyte    neg
4      endothelial-pos.pattern_0        24805    endothelial    pos
..                           ...          ...            ...    ...
83  cardiomyocyte-pos.pattern_40           27  cardiomyocyte    pos
84    endothelial-pos.pattern_39           25    endothelial    pos
85    endothelial-pos.pattern_40           23    endothelial    pos
86    endothelial-pos.pattern_41           22    endothelial    pos
87    endothelial-pos.pattern_42           21    endothelial    pos

    avg_dist_from_summit  cluster_id              annotation
0             114.309091          41        NFYrepressive_41
1              81.700000          42      YY1-2repressive_42
2              53.630435          43  ZBT7A.H13CORE.0.P.B_43
3              46.090909          44             ZEB-SNAI_44
4              45.475912          45        ETS:ELF-ETV#1_45
..                   ...         ...                     ...
83             29.444444          39         HD:MEIS-TGIF_39
84             93.160000          71                 HSF1_71
85             53.347826          73              Unknown_73
86             43.545455          74                SOX#1_74
87             37.571429          75                RFX#1_75

[88 rows x 7 columns]
--- Images ---
[]

# 4 - Conclusion

This tutorial described all the ways in which you can interact with and manipulate MotifCompendium objects and their internal parameters. Hopefully, this will help you work with MotifCompendium objects in a more flexible and object-oriented way.

Thank you so much for trying out MotifCompendium!